### ISSUE TITLE
I used your plugin but it threw me some error

### ISSUE THREAD

**Issue by Tushargupta9800** [tazik561/FlutterMp3FinderPlugin#2]
# When i run the app on my phone it threw me the following error

C:\Users\91895\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flute_music_player-0.0.6\android\src\main\java\com\mtechviral\musicfinder\MusicHelper.java:8: error: cannot find symbol
import android.support.v4.app.ActivityCompat;
                             ^
  symbol:   class ActivityCompat
  location: package android.support.v4.app
C:\Users\91895\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flute_music_player-0.0.6\android\src\main\java\com\mtechviral\musicfinder\MusicHelper.java:9: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^
C:\Users\91895\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flute_music_player-0.0.6\android\src\main\java\com\mtechviral\musicfinder\MusicHelper.java:10: error: package android.support.v7.app does not exist
import android.support.v7.app.AppCompatActivity;
                             ^
C:\Users\91895\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flute_music_player-0.0.6\android\src\main\java\com\mtechviral\musicfinder\MusicHelper.java:15: error: cannot find symbol
    public static boolean hasExternalStorageAccess(AppCompatActivity activity) {
                                                   ^
  symbol:   class AppCompatActivity
  location: class MusicHelper
C:\Users\91895\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flute_music_player-0.0.6\android\src\main\java\com\mtechviral\musicfinder\MusicHelper.java:16: error: cannot find symbol
        if(ContextCompat.checkSelfPermission(activity, Manifest.permission.READ_EXTERNAL_STORAGE)
           ^
  symbol:   variable ContextCompat
  location: class MusicHelper
C:\Users\91895\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flute_music_player-0.0.6\android\src\main\java\com\mtechviral\musicfinder\MusicHelper.java:19: error: cannot find symbol
        ActivityCompat.requestPermissions(activity,
        ^
  symbol:   variable ActivityCompat
  location: class MusicHelper
Note: C:\Users\91895\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flute_music_player-0.0.6\android\src\main\java\com\mtechviral\musicfinder\MusicFinderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\91895\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flute_music_player-0.0.6\android\src\main\java\com\mtechviral\musicfinder\MusicFinderPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flute_music_player:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 52s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin audioplayers...
Running Gradle task 'assembleAarRelease'...

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

Exception: The plugin audioplayers could not be built due to the issue above.

# Please help me with it, thanks in advance.

**Comment by Tushargupta9800** [comment]
# I tried your plugin again but this time it shows me another error.

MissingPluginException(No implementation found for method scanDeviceForMp3Files on channel flutter_mp3_finder)

## Please help! waiting for your reply.

**Comment by tazik561** [comment]
Thanks for opening issue.
I check library but i do not get problem so please open your android folder with android studio and let to android studio to sync gradle.
